# Generated by Django 2.2.4 on 2019-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190907_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.TextField(default='', verbose_name='复写username'),
        ),
    ]
