# Generated by Django 2.2.4 on 2019-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190930_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.TextField(verbose_name='复写先前的username'),
        ),
    ]
