# Generated by Django 2.2.4 on 2019-10-01 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件ID')),
                ('uid', models.CharField(max_length=50, verbose_name='上传人OpenID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('src', models.TextField(verbose_name='文件地址')),
            ],
        ),
    ]
