# Generated by Django 2.2.4 on 2019-09-30 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResouceDic',
            fields=[
                ('dicid', models.AutoField(primary_key=True, serialize=False, verbose_name='文件夹id')),
                ('userid', models.TextField(verbose_name='user的openid')),
                ('name', models.TextField(verbose_name='文件夹名字')),
                ('parent', models.TextField(verbose_name='父级目录id')),
            ],
        ),
        migrations.CreateModel(
            name='ResouceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40, verbose_name='tag名称')),
                ('desc', models.TextField(verbose_name='描述，可选')),
                ('picURL', models.TextField(verbose_name='图片，可选')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resid', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('name', models.CharField(default='res', max_length=50)),
                ('resURL', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('picURLs', models.TextField()),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResouceFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('resid', models.TextField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
            ],
            options={
                'unique_together': {('userid', 'resid')},
            },
        ),
    ]
