# Generated by Django 2.2.4 on 2019-08-30 02:12

from django.db import migrations, models
import res.models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_auto_20190827_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resoucefolder',
            name='resid',
            field=models.TextField(verbose_name=res.models.Resource),
        ),
        migrations.AlterField(
            model_name='resoucefolder',
            name='userid',
            field=models.TextField(verbose_name=res.models.User),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resURL',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='resoucefolder',
            unique_together=set(),
        ),
    ]
