# Generated by Django 2.2.4 on 2019-10-03 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_resoucefolder_is_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResouceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('resid', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('score', models.FloatField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
