# Generated by Django 2.2.4 on 2019-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_resoucecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='score',
            field=models.FloatField(default=4.5),
        ),
    ]
