# Generated by Django 2.2.4 on 2019-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_auto_20190830_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resoucefolder',
            name='resid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resoucefolder',
            name='userid',
            field=models.TextField(),
        ),
    ]
