# Generated by Django 2.2.4 on 2019-09-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_auto_20190907_2157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resoucefolder',
            unique_together={('userid', 'resid')},
        ),
    ]
