# Generated by Django 2.2.4 on 2019-10-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=40)),
                ('majorName', models.CharField(max_length=40)),
            ],
        ),
    ]
