# Generated by Django 2.2.4 on 2019-10-01 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('uid', models.CharField(max_length=50, verbose_name='评论人OpenID')),
                ('sid', models.IntegerField(verbose_name='帖子ID')),
                ('comment', models.CharField(max_length=200, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('uid', models.CharField(max_length=50, verbose_name='评论人OpenID')),
                ('sid', models.IntegerField(verbose_name='帖子ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ShareModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='帖子ID')),
                ('uid', models.CharField(max_length=50, verbose_name='发帖人OpenID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('title', models.CharField(max_length=50, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('comment', models.IntegerField(default=0, verbose_name='评论总数')),
                ('like', models.IntegerField(default=0, verbose_name='点赞总数')),
                ('store', models.IntegerField(default=0, verbose_name='收藏总数')),
            ],
        ),
        migrations.CreateModel(
            name='ShareStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('uid', models.CharField(max_length=50, verbose_name='评论人OpenID')),
                ('sid', models.IntegerField(verbose_name='帖子ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
    ]
